name: .NET

on:
  push:
    branches: [ main ]

env:
  PACKAGE_OUTPUT: ${{github.workspace}}\output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --output ${{env.PACKAGE_OUTPUT}}

    - name: Push
      run: dotnet nuget push ${{env.PACKAGE_OUTPUT}}\*.nupkg -k ${{secerts.API_KEY}} -s 'https://api.nuget.org/v3/index.json'
